# Generated by Django 3.2.7 on 2021-10-23 20:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('icon', models.CharField(max_length=255, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Элемент контактов',
                'verbose_name_plural': 'Элементы контактов',
            },
        ),
    ]
