# Generated by Django 3.2.7 on 2021-10-24 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteelements', '0002_alter_sitelogo_options'),
        ('contacts', '0002_contactitem_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactitem',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_items', to='siteelements.contact', verbose_name='раздел контакт'),
        ),
    ]
