# Generated by Django 3.2.7 on 2021-10-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteelements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitelogo',
            options={'verbose_name': 'Логотип сайта', 'verbose_name_plural': 'Логотип сайта'},
        ),
    ]
