# Generated by Django 3.2.7 on 2021-10-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteelements', '0002_alter_sitelogo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('wallpaper', models.ImageField(max_length=255, upload_to='walpaper', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Домашняя страница',
                'verbose_name_plural': 'Домашняя страница',
            },
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
