# Generated by Django 3.2.7 on 2021-10-29 10:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteelements', '0005_auto_20211028_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='text_footer',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст футера'),
        ),
    ]
