# Generated by Django 3.2.7 on 2021-10-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteelements', '0006_homepage_text_footer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='text_footer',
            new_name='footer_text',
        ),
    ]
