# Generated by Django 3.2.7 on 2021-10-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteelements', '0007_rename_text_footer_homepage_footer_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallpaper', models.ImageField(max_length=255, upload_to='article', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Вход Изображение',
                'verbose_name_plural': 'Вход Изображение',
            },
        ),
        migrations.CreateModel(
            name='PropertyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallpaper', models.ImageField(max_length=255, upload_to='article', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Недвижимость Изображение',
                'verbose_name_plural': 'Недвижимость Изображение',
            },
        ),
        migrations.CreateModel(
            name='RegisterPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallpaper', models.ImageField(max_length=255, upload_to='article', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Регистрация Изображение',
                'verbose_name_plural': 'Регистрация Изображение',
            },
        ),
    ]
