# Generated by Django 3.2.7 on 2021-11-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteelements', '0008_loginpage_propertypage_registerpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error404Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('wallpaper', models.ImageField(max_length=255, upload_to='errors', verbose_name='Изображение')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Регистрация Изображение',
                'verbose_name_plural': 'Регистрация Изображение',
            },
        ),
    ]
