# Generated by Django 3.2.7 on 2021-11-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteelements', '0009_error404page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='error404page',
            options={'verbose_name': '404', 'verbose_name_plural': '404'},
        ),
        migrations.AddField(
            model_name='legalinfo',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='legalinfo',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='usefullarticle',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='usefullarticle',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
