# Generated by Django 3.2.7 on 2021-11-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteelements', '0010_auto_20211101_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalinfo',
            options={'verbose_name': 'Юр инфа.', 'verbose_name_plural': 'Юр инфа.'},
        ),
        migrations.AlterModelOptions(
            name='loginpage',
            options={'verbose_name': 'Вход', 'verbose_name_plural': 'Вход'},
        ),
        migrations.AlterModelOptions(
            name='propertypage',
            options={'verbose_name': 'Недвижимость', 'verbose_name_plural': 'Недвижимость'},
        ),
        migrations.AlterModelOptions(
            name='registerpage',
            options={'verbose_name': 'Регистрация', 'verbose_name_plural': 'Регистрация'},
        ),
        migrations.AlterModelOptions(
            name='usefullarticle',
            options={'verbose_name': 'Полезные статьи', 'verbose_name_plural': 'Полезные статьи'},
        ),
        migrations.AddField(
            model_name='contact',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='wallpaper',
            field=models.ImageField(max_length=255, upload_to='homepage', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='loginpage',
            name='wallpaper',
            field=models.ImageField(max_length=255, upload_to='login', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='propertypage',
            name='wallpaper',
            field=models.ImageField(max_length=255, upload_to='properties', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='registerpage',
            name='wallpaper',
            field=models.ImageField(max_length=255, upload_to='register', verbose_name='Изображение'),
        ),
    ]
