# Generated by Django 3.2.7 on 2021-11-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteelements', '0011_auto_20211101_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypage',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
