# Generated by Django 3.2.7 on 2021-11-19 11:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteelements', '0012_auto_20211101_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address_additional_en',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный адрес'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_additional_mn',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный адрес'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_additional_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный адрес'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_basic_en',
            field=models.TextField(blank=True, null=True, verbose_name='Основной адрес'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_basic_mn',
            field=models.TextField(blank=True, null=True, verbose_name='Основной адрес'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_basic_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Основной адрес'),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_mn',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_mn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='error404page',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='error404page',
            name='text_mn',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='error404page',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='error404page',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='error404page',
            name='title_mn',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='error404page',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='faq',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='faq',
            name='subtitle_mn',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='faq',
            name='subtitle_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_mn',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст футера'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_text_mn',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст футера'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст футера'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle_mn',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_mn',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='legalinfo',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='legalinfo',
            name='text_mn',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='legalinfo',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='legalinfo',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='legalinfo',
            name='title_mn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='legalinfo',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='text_mn',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='title_mn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='usefullarticle',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='usefullarticle',
            name='text_mn',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='usefullarticle',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='usefullarticle',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='usefullarticle',
            name='title_mn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='usefullarticle',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
