# Generated by Django 3.2.7 on 2021-11-19 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteelements', '0014_auto_20211119_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_additional',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Дополнительный телефон'),
        ),
        migrations.CreateModel(
            name='SubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпункт меню')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпункт меню')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпункт меню')),
                ('title_mn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпункт меню')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenu_items', to='siteelements.menuitem')),
            ],
            options={
                'verbose_name': 'Подпункт меню',
                'verbose_name_plural': 'Подпункты меню',
            },
        ),
    ]
