# Generated by Django 3.2.7 on 2021-11-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteelements', '0015_auto_20211119_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='submenuitem',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ссылка'),
        ),
    ]
