# Generated by Django 3.2.7 on 2021-11-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteelements', '0018_alter_menuitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_title', models.CharField(default='Тип объекта', max_length=255, verbose_name='Заголовок тип объекта')),
                ('type_title_ru', models.CharField(default='Тип объекта', max_length=255, null=True, verbose_name='Заголовок тип объекта')),
                ('type_title_en', models.CharField(default='Тип объекта', max_length=255, null=True, verbose_name='Заголовок тип объекта')),
                ('type_title_mn', models.CharField(default='Тип объекта', max_length=255, null=True, verbose_name='Заголовок тип объекта')),
                ('area_title', models.CharField(default='Метраж', max_length=255, verbose_name='Заголовок метраж')),
                ('area_title_ru', models.CharField(default='Метраж', max_length=255, null=True, verbose_name='Заголовок метраж')),
                ('area_title_en', models.CharField(default='Метраж', max_length=255, null=True, verbose_name='Заголовок метраж')),
                ('area_title_mn', models.CharField(default='Метраж', max_length=255, null=True, verbose_name='Заголовок метраж')),
                ('property_id_title', models.CharField(default='Id объекта', max_length=255, verbose_name='Заголовок Id объекта')),
                ('property_id_title_ru', models.CharField(default='Id объекта', max_length=255, null=True, verbose_name='Заголовок Id объекта')),
                ('property_id_title_en', models.CharField(default='Id объекта', max_length=255, null=True, verbose_name='Заголовок Id объекта')),
                ('property_id_title_mn', models.CharField(default='Id объекта', max_length=255, null=True, verbose_name='Заголовок Id объекта')),
                ('bathroom_title', models.CharField(default='Санузлов', max_length=255, verbose_name='Заголовок санузел')),
                ('bathroom_title_ru', models.CharField(default='Санузлов', max_length=255, null=True, verbose_name='Заголовок санузел')),
                ('bathroom_title_en', models.CharField(default='Санузлов', max_length=255, null=True, verbose_name='Заголовок санузел')),
                ('bathroom_title_mn', models.CharField(default='Санузлов', max_length=255, null=True, verbose_name='Заголовок санузел')),
                ('bedroom_iitle', models.CharField(default='Спальни', max_length=255, verbose_name='Заголовок спальня')),
                ('bedroom_iitle_ru', models.CharField(default='Спальни', max_length=255, null=True, verbose_name='Заголовок спальня')),
                ('bedroom_iitle_en', models.CharField(default='Спальни', max_length=255, null=True, verbose_name='Заголовок спальня')),
                ('bedroom_iitle_mn', models.CharField(default='Спальни', max_length=255, null=True, verbose_name='Заголовок спальня')),
                ('region_title', models.CharField(default='Регион', max_length=255, verbose_name='Заголовок регион')),
                ('region_title_ru', models.CharField(default='Регион', max_length=255, null=True, verbose_name='Заголовок регион')),
                ('region_title_en', models.CharField(default='Регион', max_length=255, null=True, verbose_name='Заголовок регион')),
                ('region_title_mn', models.CharField(default='Регион', max_length=255, null=True, verbose_name='Заголовок регион')),
            ],
            options={
                'verbose_name': 'Заголовоки Характеристик ',
                'verbose_name_plural': 'Заголовоки Характеристик',
            },
        ),
        migrations.AddField(
            model_name='faq',
            name='call_us_button',
            field=models.CharField(default='Позвонить', max_length=255, verbose_name='Кнопка'),
        ),
        migrations.AddField(
            model_name='faq',
            name='call_us_text',
            field=models.CharField(default='У вас возникли вопросы, жалобы, или предложения? Просто позвоните нам.', max_length=255, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='faq',
            name='call_us_title',
            field=models.CharField(default='Все просто', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='login',
            field=models.CharField(default='Вход для агентов', max_length=255, verbose_name='Вход для агентов'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='login_en',
            field=models.CharField(default='Вход для агентов', max_length=255, null=True, verbose_name='Вход для агентов'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='login_mn',
            field=models.CharField(default='Вход для агентов', max_length=255, null=True, verbose_name='Вход для агентов'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='login_ru',
            field=models.CharField(default='Вход для агентов', max_length=255, null=True, verbose_name='Вход для агентов'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='trend_subtitle',
            field=models.CharField(default='Наши лучшие объекты', max_length=255, verbose_name='В тренде  Подзаголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='trend_subtitle_en',
            field=models.CharField(default='Наши лучшие объекты', max_length=255, null=True, verbose_name='В тренде  Подзаголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='trend_subtitle_mn',
            field=models.CharField(default='Наши лучшие объекты', max_length=255, null=True, verbose_name='В тренде  Подзаголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='trend_subtitle_ru',
            field=models.CharField(default='Наши лучшие объекты', max_length=255, null=True, verbose_name='В тренде  Подзаголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='trend_title',
            field=models.CharField(default='В тренде', max_length=255, verbose_name='В тренде Заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='trend_title_en',
            field=models.CharField(default='В тренде', max_length=255, null=True, verbose_name='В тренде Заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='trend_title_mn',
            field=models.CharField(default='В тренде', max_length=255, null=True, verbose_name='В тренде Заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='trend_title_ru',
            field=models.CharField(default='В тренде', max_length=255, null=True, verbose_name='В тренде Заголовок'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='features_title',
            field=models.CharField(default='Характеристики', max_length=255, verbose_name='Заголовок характеристик объекта'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='features_title_en',
            field=models.CharField(default='Характеристики', max_length=255, null=True, verbose_name='Заголовок характеристик объекта'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='features_title_mn',
            field=models.CharField(default='Характеристики', max_length=255, null=True, verbose_name='Заголовок характеристик объекта'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='features_title_ru',
            field=models.CharField(default='Характеристики', max_length=255, null=True, verbose_name='Заголовок характеристик объекта'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='filter_title',
            field=models.CharField(default='Фильтр объектов', max_length=255, verbose_name='Заголовок фильтра'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='filter_title_en',
            field=models.CharField(default='Фильтр объектов', max_length=255, null=True, verbose_name='Заголовок фильтра'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='filter_title_mn',
            field=models.CharField(default='Фильтр объектов', max_length=255, null=True, verbose_name='Заголовок фильтра'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='filter_title_ru',
            field=models.CharField(default='Фильтр объектов', max_length=255, null=True, verbose_name='Заголовок фильтра'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='more_button',
            field=models.CharField(default='Подробнее', max_length=255, verbose_name='Кнопка подробнее'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='more_button_en',
            field=models.CharField(default='Подробнее', max_length=255, null=True, verbose_name='Кнопка подробнее'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='more_button_mn',
            field=models.CharField(default='Подробнее', max_length=255, null=True, verbose_name='Кнопка подробнее'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='more_button_ru',
            field=models.CharField(default='Подробнее', max_length=255, null=True, verbose_name='Кнопка подробнее'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='new_property_title',
            field=models.CharField(default='Новые объекты', max_length=255, verbose_name='Заголовок нвых объектов'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='new_property_title_en',
            field=models.CharField(default='Новые объекты', max_length=255, null=True, verbose_name='Заголовок нвых объектов'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='new_property_title_mn',
            field=models.CharField(default='Новые объекты', max_length=255, null=True, verbose_name='Заголовок нвых объектов'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='new_property_title_ru',
            field=models.CharField(default='Новые объекты', max_length=255, null=True, verbose_name='Заголовок нвых объектов'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='property_description_title',
            field=models.CharField(default='Описание объекта', max_length=255, verbose_name='Заголовок описания объекта'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='property_description_title_en',
            field=models.CharField(default='Описание объекта', max_length=255, null=True, verbose_name='Заголовок описания объекта'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='property_description_title_mn',
            field=models.CharField(default='Описание объекта', max_length=255, null=True, verbose_name='Заголовок описания объекта'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='property_description_title_ru',
            field=models.CharField(default='Описание объекта', max_length=255, null=True, verbose_name='Заголовок описания объекта'),
        ),
    ]
