# Generated by Django 3.2.7 on 2021-11-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteelements', '0019_auto_20211127_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(default='Меню', max_length=255, verbose_name='Пункт меню')),
                ('menu_title_ru', models.CharField(default='Меню', max_length=255, null=True, verbose_name='Пункт меню')),
                ('menu_title_en', models.CharField(default='Меню', max_length=255, null=True, verbose_name='Пункт меню')),
                ('menu_title_mn', models.CharField(default='Меню', max_length=255, null=True, verbose_name='Пункт меню')),
                ('social_title', models.CharField(default='соцсети', max_length=255, verbose_name='Пункт соцсети')),
                ('social_title_ru', models.CharField(default='соцсети', max_length=255, null=True, verbose_name='Пункт соцсети')),
                ('social_title_en', models.CharField(default='соцсети', max_length=255, null=True, verbose_name='Пункт соцсети')),
                ('social_title_mn', models.CharField(default='соцсети', max_length=255, null=True, verbose_name='Пункт соцсети')),
                ('messenger_title', models.CharField(default='мессенджеры', max_length=255, verbose_name='Пункт мессенджеры')),
                ('messenger_title_ru', models.CharField(default='мессенджеры', max_length=255, null=True, verbose_name='Пункт мессенджеры')),
                ('messenger_title_en', models.CharField(default='мессенджеры', max_length=255, null=True, verbose_name='Пункт мессенджеры')),
                ('messenger_title_mn', models.CharField(default='мессенджеры', max_length=255, null=True, verbose_name='Пункт мессенджеры')),
            ],
            options={
                'verbose_name': 'Мобильное меню',
                'verbose_name_plural': 'Мобильное меню',
            },
        ),
    ]
