# Generated by Django 3.2.7 on 2021-11-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteelements', '0020_mobilemenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='search_button',
            field=models.CharField(default='Поиск объектов', max_length=255, verbose_name='Кнопка поиск'),
        ),
    ]
