# Generated by Django 3.2.7 on 2021-12-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteelements', '0022_auto_20211127_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='call_us_button_en',
            field=models.CharField(default='Позвонить', max_length=255, null=True, verbose_name='Кнопка'),
        ),
        migrations.AddField(
            model_name='faq',
            name='call_us_button_mn',
            field=models.CharField(default='Позвонить', max_length=255, null=True, verbose_name='Кнопка'),
        ),
        migrations.AddField(
            model_name='faq',
            name='call_us_button_ru',
            field=models.CharField(default='Позвонить', max_length=255, null=True, verbose_name='Кнопка'),
        ),
        migrations.AddField(
            model_name='faq',
            name='call_us_text_en',
            field=models.CharField(default='У вас возникли вопросы, жалобы, или предложения? Просто позвоните нам.', max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='faq',
            name='call_us_text_mn',
            field=models.CharField(default='У вас возникли вопросы, жалобы, или предложения? Просто позвоните нам.', max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='faq',
            name='call_us_text_ru',
            field=models.CharField(default='У вас возникли вопросы, жалобы, или предложения? Просто позвоните нам.', max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='faq',
            name='call_us_title_en',
            field=models.CharField(default='Все просто', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='faq',
            name='call_us_title_mn',
            field=models.CharField(default='Все просто', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='faq',
            name='call_us_title_ru',
            field=models.CharField(default='Все просто', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='propertypage',
            name='new_property_title',
            field=models.CharField(default='Новые объекты', max_length=255, verbose_name='Заголовок новых объектов'),
        ),
        migrations.AlterField(
            model_name='propertypage',
            name='new_property_title_en',
            field=models.CharField(default='Новые объекты', max_length=255, null=True, verbose_name='Заголовок новых объектов'),
        ),
        migrations.AlterField(
            model_name='propertypage',
            name='new_property_title_mn',
            field=models.CharField(default='Новые объекты', max_length=255, null=True, verbose_name='Заголовок новых объектов'),
        ),
        migrations.AlterField(
            model_name='propertypage',
            name='new_property_title_ru',
            field=models.CharField(default='Новые объекты', max_length=255, null=True, verbose_name='Заголовок новых объектов'),
        ),
    ]
