# Generated by Django 3.2.7 on 2021-12-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteelements', '0023_auto_20211202_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypage',
            name='video_title',
            field=models.CharField(default='Видео объекта', max_length=255, verbose_name='Заголовок Видео объекта'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='video_title_en',
            field=models.CharField(default='Видео объекта', max_length=255, null=True, verbose_name='Заголовок Видео объекта'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='video_title_mn',
            field=models.CharField(default='Видео объекта', max_length=255, null=True, verbose_name='Заголовок Видео объекта'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='video_title_ru',
            field=models.CharField(default='Видео объекта', max_length=255, null=True, verbose_name='Заголовок Видео объекта'),
        ),
    ]
