# Generated by Django 3.2.7 on 2021-10-27 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_rename_sub_title_logo_subtitle'),
        ('accounts', '0002_user_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='images.logo', verbose_name='Логотип'),
        ),
    ]
