# Generated by Django 3.2.7 on 2021-10-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='unique_id',
            field=models.CharField(default='adria-2021-10-23 23:28:47.616999', max_length=255, unique=True, verbose_name='Артикул'),
        ),
    ]
