# Generated by Django 3.2.7 on 2021-10-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20211024_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='property',
            name='unique_id',
            field=models.CharField(default='adria-2021-10-24 10:42:53.819035', max_length=255, unique=True, verbose_name='Артикул'),
        ),
    ]
