# Generated by Django 3.2.7 on 2021-10-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20211024_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='unique_id',
            field=models.CharField(default='adria-2021-10-24 17:20:43.548515', max_length=255, unique=True, verbose_name='Артикул'),
        ),
    ]
