# Generated by Django 3.2.7 on 2021-10-25 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_property_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateField(default=datetime.date(2021, 10, 25), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='property',
            name='unique_id',
            field=models.CharField(default='adria-2021-10-25 13:11:51.175340', max_length=255, unique=True, verbose_name='Артикул'),
        ),
    ]
