# Generated by Django 3.2.7 on 2021-10-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20211025_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', '-id'], 'verbose_name': 'Категории', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AddField(
            model_name='property',
            name='is_trend',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='unique_id',
            field=models.CharField(default='adria-2021-10-25-13-36-17', max_length=255, unique=True, verbose_name='Артикул'),
        ),
    ]
