# Generated by Django 3.2.7 on 2021-10-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20211025_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='unique_id',
            field=models.CharField(default='adria-2021-10-25-13-38-25', max_length=255, unique=True, verbose_name='Артикул'),
        ),
    ]
