# Generated by Django 3.2.7 on 2021-10-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_property_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.ManyToManyField(related_name='properties', to='properties.Status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='property',
            name='unique_id',
            field=models.CharField(default='adria-2021-10-25-15-57-03', max_length=255, unique=True, verbose_name='Артикул'),
        ),
    ]
