# Generated by Django 3.2.7 on 2021-10-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_auto_20211026_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='unique_id',
            field=models.CharField(default='adria-2021-10-26-18-02-56', max_length=255, unique=True, verbose_name='Артикул'),
        ),
    ]
