# Generated by Django 3.2.7 on 2021-10-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_alter_property_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='unique_id',
            field=models.CharField(default='adria-2021-10-26-15-29-59', max_length=255, unique=True, verbose_name='Артикул'),
        ),
    ]
