# Generated by Django 3.2.7 on 2021-10-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_auto_20211026_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='unique_id',
            field=models.CharField(default='adria-2021-10-27-09-09-53', max_length=255, unique=True, verbose_name='Артикул'),
        ),
    ]
