# Generated by Django 3.2.7 on 2021-10-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_auto_20211027_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='unique_id',
            field=models.CharField(default='adria-2021-10-27-09-26-52', max_length=255, unique=True, verbose_name='Артикул'),
        ),
    ]
