# Generated by Django 3.2.7 on 2021-10-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_auto_20211027_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Особенность', 'verbose_name_plural': 'Особенности'},
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(max_length=55, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='property',
            name='unique_id',
            field=models.CharField(default='adria-2021-10-27-09-34-56', max_length=255, unique=True, verbose_name='Артикул'),
        ),
    ]
