# Generated by Django 3.2.7 on 2021-10-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_alter_property_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул'),
        ),
    ]
