# Generated by Django 3.2.7 on 2021-10-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_auto_20211027_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Видео'),
        ),
    ]
