# Generated by Django 3.2.7 on 2021-10-28 14:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_property_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
