# Generated by Django 3.2.7 on 2021-11-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0036_filterdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filterdata',
            options={'verbose_name': 'Фильтр', 'verbose_name_plural': 'Фильтр'},
        ),
    ]
