# Generated by Django 3.2.7 on 2021-11-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0037_alter_filterdata_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='features',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
