# Generated by Django 3.2.7 on 2021-12-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0038_auto_20211127_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterdata',
            name='regions_any',
            field=models.CharField(default='Любой регион', max_length=255, verbose_name='Любой регион'),
        ),
        migrations.AddField(
            model_name='filterdata',
            name='regions_any_en',
            field=models.CharField(default='Любой регион', max_length=255, null=True, verbose_name='Любой регион'),
        ),
        migrations.AddField(
            model_name='filterdata',
            name='regions_any_mn',
            field=models.CharField(default='Любой регион', max_length=255, null=True, verbose_name='Любой регион'),
        ),
        migrations.AddField(
            model_name='filterdata',
            name='regions_any_ru',
            field=models.CharField(default='Любой регион', max_length=255, null=True, verbose_name='Любой регион'),
        ),
        migrations.AddField(
            model_name='filterdata',
            name='regions_title',
            field=models.CharField(default='Регион', max_length=255, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='filterdata',
            name='regions_title_en',
            field=models.CharField(default='Регион', max_length=255, null=True, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='filterdata',
            name='regions_title_mn',
            field=models.CharField(default='Регион', max_length=255, null=True, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='filterdata',
            name='regions_title_ru',
            field=models.CharField(default='Регион', max_length=255, null=True, verbose_name='Регион'),
        ),
    ]
