# Generated by Django 3.2.7 on 2021-12-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0040_filterdata_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterdata',
            name='price_range_en',
            field=models.CharField(default='Диапазон цен', max_length=255, null=True, verbose_name='Диапазон цен'),
        ),
        migrations.AddField(
            model_name='filterdata',
            name='price_range_mn',
            field=models.CharField(default='Диапазон цен', max_length=255, null=True, verbose_name='Диапазон цен'),
        ),
        migrations.AddField(
            model_name='filterdata',
            name='price_range_ru',
            field=models.CharField(default='Диапазон цен', max_length=255, null=True, verbose_name='Диапазон цен'),
        ),
    ]
