# Generated by Django 3.2.7 on 2021-10-23 16:51

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('image', models.ImageField(max_length=255, upload_to=images.models.logo_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Логотип',
                'verbose_name_plural': 'Логотипы',
                'ordering': ['-id'],
            },
        ),
    ]
