# Generated by Django 3.2.7 on 2021-10-23 19:01

from django.db import migrations, models
import django.db.models.deletion
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=images.models.logo_path, verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to=images.models.property_image_path, verbose_name='Изображение')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_gallary', to='properties.property', verbose_name='Недвижимость')),
            ],
        ),
    ]
