# Generated by Django 3.2.7 on 2021-10-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20211023_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['-id'], 'verbose_name': 'Изображение недвижимости', 'verbose_name_plural': 'Галерея недвижимости'},
        ),
    ]
