# Generated by Django 3.2.7 on 2021-10-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_propertyimage_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='sub_title',
            new_name='subtitle',
        ),
    ]
