# Generated by Django 3.2.7 on 2021-10-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_rename_sub_title_logo_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='property',
            new_name='image_property',
        ),
    ]
