# Generated by Django 3.2.7 on 2021-11-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_propertyimage_image_property'),
    ]

    operations = []
