# Generated by Django 3.2.7 on 2021-10-23 20:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Вопрос')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Элемент FAQ',
                'verbose_name_plural': 'Элементы FAQ',
            },
        ),
        migrations.CreateModel(
            name='LegalInfoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Элемент юр инфы',
                'verbose_name_plural': 'Элементы юр инфы',
            },
        ),
    ]
