# Generated by Django 3.2.7 on 2021-10-23 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legals', '0001_initial'),
        ('siteelements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalinfoitem',
            name='legal_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_info_items', to='siteelements.legalinfo', verbose_name='Юр инфа'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='faq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='siteelements.faq', verbose_name='FAQ'),
        ),
    ]
