# Generated by Django 3.2.7 on 2021-10-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='legalinfoitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
