# Generated by Django 3.2.7 on 2021-11-19 10:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legals', '0005_auto_20211028_1745'),
    ]

    operations = []
