# Generated by Django 3.2.7 on 2021-11-19 11:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legals', '0006_auto_20211119_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='answer_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='answer_mn',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='answer_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='question_en',
            field=models.TextField(null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='question_mn',
            field=models.TextField(null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='question_ru',
            field=models.TextField(null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='legalinfoitem',
            name='body_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='legalinfoitem',
            name='body_mn',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='legalinfoitem',
            name='body_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='legalinfoitem',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='legalinfoitem',
            name='title_mn',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='legalinfoitem',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
